/*
 * Generated by erpcgen 1.6.0 on Mon May 28 12:32:19 2018.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_uart_rpc_h_)
#define _uart_rpc_h_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "erpc_version.h"
#include "erpc_crc16.h"

#if 10600 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


#if !defined(ERPC_GENERATED_CRC) || ERPC_GENERATED_CRC != 42968
#error "Macro 'ERPC_GENERATED_CRC' should be defined with value 42968."
#endif

#if !defined(ERPC_TYPE_DEFINITIONS)
#define ERPC_TYPE_DEFINITIONS

#endif // ERPC_TYPE_DEFINITIONS

/*! @brief TEST_UART identifiers */
enum _TEST_UART_ids
{
    kTEST_UART_service_id = 1,
    kTEST_UART_turnGreenLEDON_id = 1,
    kTEST_UART_turnGreenLEDOFF_id = 2,
};

#if defined(__cplusplus)
extern "C" {
#endif

//! @name TEST_UART
//@{
void turnGreenLEDON(void);

void turnGreenLEDOFF(void);
//@} 

#if defined(__cplusplus)
}
#endif

#endif // _uart_rpc_h_
