#
# Generated by erpcgen 1.6.0 on Mon May 28 12:32:19 2018.
#
# AUTOGENERATED - DO NOT EDIT
#

import erpc

# Abstract base class for TEST_UART
class ITEST_UART(object):
    SERVICE_ID = 1
    TURNGREENLEDON_ID = 1
    TURNGREENLEDOFF_ID = 2

    def turnGreenLEDON(self):
        raise NotImplementedError()

    def turnGreenLEDOFF(self):
        raise NotImplementedError()


