#
# Generated by erpcgen 1.6.0 on Mon May 28 12:32:19 2018.
#
# AUTOGENERATED - DO NOT EDIT
#

import erpc
from . import common, interface

# Client for TEST_UART
class TEST_UARTService(erpc.server.Service):
    def __init__(self, handler):
        super(TEST_UARTService, self).__init__(interface.ITEST_UART.SERVICE_ID)
        self._handler = handler
        self._methods = {
                interface.ITEST_UART.TURNGREENLEDON_ID: self._handle_turnGreenLEDON,
                interface.ITEST_UART.TURNGREENLEDOFF_ID: self._handle_turnGreenLEDOFF,
            }

    def _handle_turnGreenLEDON(self, sequence, codec):
        # Read incoming parameters.

        # Invoke user implementation of remote function.
        self._handler.turnGreenLEDON()

        # Prepare codec for reply message.
        codec.reset()

        # Construct reply message.
        codec.start_write_message(erpc.codec.MessageInfo(
            type=erpc.codec.MessageType.kReplyMessage,
            service=interface.ITEST_UART.SERVICE_ID,
            request=interface.ITEST_UART.TURNGREENLEDON_ID,
            sequence=sequence))

    def _handle_turnGreenLEDOFF(self, sequence, codec):
        # Read incoming parameters.

        # Invoke user implementation of remote function.
        self._handler.turnGreenLEDOFF()

        # Prepare codec for reply message.
        codec.reset()

        # Construct reply message.
        codec.start_write_message(erpc.codec.MessageInfo(
            type=erpc.codec.MessageType.kReplyMessage,
            service=interface.ITEST_UART.SERVICE_ID,
            request=interface.ITEST_UART.TURNGREENLEDOFF_ID,
            sequence=sequence))


