#
# Generated by erpcgen 1.6.0 on Mon May  7 13:54:12 2018.
#
# AUTOGENERATED - DO NOT EDIT
#

import erpc

# Abstract base class for IO
class IIO(object):
    SERVICE_ID = 1
    TURNGREENLEDON_ID = 1
    TURNGREENLEDOFF_ID = 2

    def turnGreenLEDON(self):
        raise NotImplementedError()

    def turnGreenLEDOFF(self):
        raise NotImplementedError()


