#pragma once
#ifndef THOR_RPC_HPP
#define THOR_RPC_HPP

/* eRPC Includes */
// #include <Thor/erpc/setup/erpc_server_setup.h>
// #include <Thor/erpc/transports/serial_thor_transport.h>

// /** @namespace Thor */
// namespace Thor
// {
// 	/** @namespace Thor::eRPC */
// 	namespace eRPC
// 	{
// 		/** Starts an eRPC server using a dedicated serial line and specific service
// 		 *	@param[in] serialChannel	Which serial object to use from Thor::Peripheral::Serial
// 		 *	@param[in] service			Function pointer to the service to run (function auto-generated by erpcgen)
// 		 *	@return void
// 		 */
// 		extern void erpcServerSetup(int serialChannel, void*(*service)(void));
// 	}
// }

#endif /* !THOR_RPC_HPP */