/*
 * Generated by erpcgen 1.6.0 on Mon May  7 13:51:33 2018.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_led_h_)
#define _led_h_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "erpc_version.h"
#include "erpc_crc16.h"

#if 10600 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


#if !defined(ERPC_GENERATED_CRC) || ERPC_GENERATED_CRC != 49684
#error "Macro 'ERPC_GENERATED_CRC' should be defined with value 49684."
#endif

#if !defined(ERPC_TYPE_DEFINITIONS)
#define ERPC_TYPE_DEFINITIONS

#endif // ERPC_TYPE_DEFINITIONS

/*! @brief IO identifiers */
enum _IO_ids
{
    kIO_service_id = 1,
    kIO_turnGreenLEDON_id = 1,
    kIO_turnGreenLEDOFF_id = 2,
};

#if defined(__cplusplus)
extern "C" {
#endif

//! @name IO
//@{
void turnGreenLEDON(void);

void turnGreenLEDOFF(void);
//@} 

#if defined(__cplusplus)
}
#endif

#endif // _led_h_
