/*
 * Generated by erpcgen 1.6.0 on Sat May 26 15:28:13 2018.
 *
 * AUTOGENERATED - DO NOT EDIT
 */

#if !defined(_erpc_crc16_h_)
#define _erpc_crc16_h_

#if !defined(ERPC_GENERATED_CRC)
#define ERPC_GENERATED_CRC 1785
#else
#error "Macro 'ERPC_GENERATED_CRC' shouldn't be defined at this moment."
#endif

#endif // _erpc_crc16_h_
