#
# Generated by erpcgen 1.6.0 on Sat May 26 15:37:33 2018.
#
# AUTOGENERATED - DO NOT EDIT
#

import erpc
from . import common, interface

# Client for IO
class IOClient(interface.IIO):
    def __init__(self, manager):
        super(IOClient, self).__init__()
        self._clientManager = manager

    def turnGreenLEDON(self):
        # Build remote function invocation message.
        request = self._clientManager.create_request()
        codec = request.codec
        codec.start_write_message(erpc.codec.MessageInfo(
                type=erpc.codec.MessageType.kInvocationMessage,
                service=self.SERVICE_ID,
                request=self.TURNGREENLEDON_ID,
                sequence=request.sequence))

        # Send request and process reply.
        self._clientManager.perform_request(request)

    def turnGreenLEDOFF(self):
        # Build remote function invocation message.
        request = self._clientManager.create_request()
        codec = request.codec
        codec.start_write_message(erpc.codec.MessageInfo(
                type=erpc.codec.MessageType.kInvocationMessage,
                service=self.SERVICE_ID,
                request=self.TURNGREENLEDOFF_ID,
                sequence=request.sequence))

        # Send request and process reply.
        self._clientManager.perform_request(request)



