#
# Generated by erpcgen 1.6.0 on Sat May 26 15:37:33 2018.
#
# AUTOGENERATED - DO NOT EDIT
#

import erpc

# Abstract base class for IO
class IIO(object):
    SERVICE_ID = 1
    TURNGREENLEDON_ID = 1
    TURNGREENLEDOFF_ID = 2

    def turnGreenLEDON(self):
        raise NotImplementedError()

    def turnGreenLEDOFF(self):
        raise NotImplementedError()


